Animated
zero-to-mastery/javascript20-projects pull request #184
Opened 2020-10-04 03:48 UTC by alaa140101

2020-10-04 14:08 UTC, MattCSmith requested changes
Hey @alaa140101 
Any chance you can remove the few lines mentioned below, they do not need to be present
thanks

2020-10-04 14:08 UTC, MattCSmith commented on README.md
> +<<<<<<< HEAD
This line

2020-10-04 14:08 UTC, MattCSmith commented on README.md
> +=======
This line

2020-10-04 14:08 UTC, MattCSmith commented on README.md
> +>>>>>>> cad64e0f792086c8c32d44b98ae83784c5507cbc
This line

2020-10-05 03:13 UTC, alaa140101 reviewed
resolved

2020-10-07 23:54 UTC, merged