Added My name in list | Quote Generator
zero-to-mastery/javascript20-projects pull request #546
Opened 2022-11-23 16:26 UTC by hussain3kb

2022-11-28 19:45 UTC, rroyo approved these changes

2022-11-28 19:45 UTC, rroyo approved these changes

2022-11-28 19:48 UTC, rroyo requested changes
These files don't belong to this repository.

2023-01-15 20:58 UTC, MattCSmith requested changes
Hey, 
This project is designed to link to students' project repos, not directly include projects. 
Please remove favicon.png, index.html, script.js and style.css so we can proceed to merge this pull request.

2023-01-19 12:07 UTC, MattCSmith commented
I'm closing this PR due to the unresolved change request. Please feel free to resolve and re-open

2023-01-19 12:07 UTC, closed without merging